# Generated by Django 4.2.1 on 2023-05-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('CaseID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='', max_length=255)),
                ('Description', models.CharField(default='', max_length=255)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('DriverName', models.CharField(default='', max_length=255)),
                ('VehicleModel', models.CharField(default='', max_length=255)),
                ('Injuries', models.CharField(default='', max_length=255)),
                ('VehicleDamage', models.CharField(default='', max_length=255)),
                ('LocationName', models.CharField(default='', max_length=255)),
                ('LocationAddress', models.CharField(default='', max_length=255)),
                ('RefItem', models.FileField(null=True, upload_to='reference_docs/')),
                ('DateCreated', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='default_filename', max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('LocationAddress', models.CharField(default='', max_length=255)),
                ('CoordLong', models.FloatField(default=0)),
                ('CoordLat', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.IntegerField(primary_key=True, serialize=False)),
                ('VehicleModel', models.CharField(default='', max_length=255)),
                ('VehicleType', models.CharField(default='', max_length=20)),
                ('VehiclePlateNumber', models.CharField(default='', max_length=10)),
                ('VehicleDamage', models.CharField(default='', max_length=255)),
                ('CaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VAASWebApp.accidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDoc',
            fields=[
                ('ReferenceID', models.IntegerField(primary_key=True, serialize=False)),
                ('RefItem', models.FileField(null=True, upload_to='reference_docs/')),
                ('OwnedBy', models.CharField(default='', max_length=100)),
                ('RefType', models.CharField(max_length=20)),
                ('CaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VAASWebApp.accidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('DriverID', models.IntegerField(primary_key=True, serialize=False)),
                ('DriverName', models.CharField(default='', max_length=255)),
                ('DriverAge', models.PositiveIntegerField()),
                ('DriverGender', models.CharField(default='', max_length=10)),
                ('DriverLicense', models.CharField(default='', max_length=255)),
                ('Injuries', models.CharField(default='', max_length=255)),
                ('CaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VAASWebApp.accidentreport')),
            ],
        ),
    ]
