# Generated by Django 4.2.1 on 2023-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='DriverID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referencedoc',
            name='ReferenceID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
