# Generated by Django 4.2.1 on 2023-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0006_alter_vehicle_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='PersonGender',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleType',
            field=models.CharField(choices=[('', ''), ('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Bus', 'Bus'), ('Truck', 'Truck'), ('Van', 'Van'), ('Other', 'Other')], max_length=20),
        ),
    ]
