# Generated by Django 4.2.1 on 2023-06-01 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0008_alter_person_persontype_alter_referencedoc_reftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='VehicleOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VAASWebApp.person'),
        ),
    ]
