# Generated by Django 4.2.1 on 2023-06-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0009_vehicle_vehicleowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='Injuries',
            field=models.TextField(),
        ),
    ]
