# Generated by Django 4.2.1 on 2023-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0010_alter_accidentreport_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedoc',
            name='ContactNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='referencedoc',
            name='RefType',
            field=models.CharField(choices=[('', ''), ('Document', 'Document'), ('Picture', 'Picture'), ('Video', 'Video'), ('Other', 'Other')], max_length=20),
        ),
    ]
