# Generated by Django 4.2.2 on 2023-06-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0011_referencedoc_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='PersonName',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VAASWebApp.person', to_field='PersonName'),
        ),
    ]
