# Generated by Django 4.2.2 on 2023-06-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0016_delete_userinfo_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='LocationAddress',
            new_name='States',
        ),
    ]
