# Generated by Django 4.2.2 on 2023-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0017_rename_locationaddress_location_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='InjuriesLevel',
            field=models.CharField(choices=[('', ''), ('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='DamageLevel',
            field=models.CharField(choices=[('', ''), ('Minor', 'Minor'), ('Major', 'Major')], default='', max_length=10),
        ),
    ]
