# Generated by Django 4.2.2 on 2023-07-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0018_person_injurieslevel_vehicle_damagelevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencedoc',
            name='ContactNumber',
        ),
    ]
