# Generated by Django 4.2.2 on 2023-07-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0020_alter_referencedoc_refitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='CoordLat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='CoordLong',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
