# Generated by Django 4.2.3 on 2023-07-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VAASWebApp', '0021_alter_location_coordlat_alter_location_coordlong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='LocationName',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='CoordLat',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='CoordLong',
            new_name='Longtitude',
        ),
    ]
